### ISSUE TITLE
Architecture about template repositories

### ISSUE THREAD

**Issue by fabiorogeriosj** [landfy/landfy#11]
I think a good approach is for each template to have its own repository in the `landfy` organization.

One difficulty is the new PR of the community, would it be nice for the PRs to first enter a validation repository and then it be migrated to an official repository?

**Comment by eptaccio** [comment]
My ideia is [something like this](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js)

A list with the 'name' and url of the template repository (hosted on the contributor github).
